### ISSUE TITLE
Autostart DebugServer on localhost

### ISSUE THREAD

**Issue by Kirpich30000** [vsrad/radeon-asm-tools#174]
Add `Autostart local DebugServer` switch in `RAD Options`. On by default.
Add `DebugServer path` in `RAD Options`. By default it should point to DebugServer installed with vsix extension.

If both `Profiles`->`Localhost` and `RAD Options`->`Autostart ...` are set then check if the DebugProcess is currently running before attempting to connect. If it's not - run DebugServer on port `Profiles`->`General`->`Port`.

**Comment by timlathy** [comment]
This won't be necessary if #173 is implemented as described in [this comment](https://github.com/vsrad/radeon-asm-tools/issues/173#issuecomment-733784082).

**Comment by Kirpich30000** [comment]
Implemented in 2021.01.22 with `Local` mode
