### ISSUE TITLE
Error handling issues

### ISSUE THREAD

**Issue by Kirpich30000** [vsrad/radeon-asm-tools#21]
- [x]  LineMapping is wrong. Presumably `SourceLine = int.Parse(match.Groups["line"].Value) - 1` should fix it
- [ ] Error messages might not have line numbers. Currently plugin doesn't process such situation correctly

**Comment by timlathy** [comment]
This issue is no longer applicable: line mapping was removed in 2d9703ce45c998bc9d28e6d3817d1f42290bcfd3 because we decided it works better as a separate script, not part of the extension code.
