### ISSUE TITLE
Function List displays incomplete functions names

### ISSUE THREAD

**Issue by johnny-keker** [vsrad/radeon-asm-tools#303]
`Function List` sometimes can fuse functions with different names. Needs to be investigated and reproduced.

**Comment by timlathy** [comment]
It looks like the function list computes text width based on the visible items and does not adjust it on scroll or when the window is resized. Adding new labels or changing existing ones does recompute the width, though.

![fl_incomplete_names](https://user-images.githubusercontent.com/32609527/182403279-01898fa3-8ae2-4f98-831a-e1269a8df46e.gif)
