### ISSUE TITLE
"Run to here" issue

### ISSUE THREAD

**Issue by Kirpich30000** [vsrad/radeon-asm-tools#49]
`Run to here` feature should ignore any existing breakpoints and breaks exactly where requested. If `continue` is pressed, next breakpoint after `Run to here` line should be activated.

**Comment by Kirpich30000** [comment]
Also `Run to here` should not be added to a list of breakpoints and should not be used when going through breakpoints using `continue`.

**Comment by johnny-keker** [comment]
`Force run to cursor` works as requested
