### ISSUE TITLE
Build results reporting

### ISSUE THREAD

**Issue by Kirpich30000** [vsrad/radeon-asm-tools#68]
Errors and warnings are not showed up in text editor if it was hidden in Error List:
![image](https://user-images.githubusercontent.com/12259057/80234675-39545800-8661-11ea-84a3-6152d0ce645d.png)
Steps to reproduce: hide errors or warnings in error list, edit source to add something to trigger error, build, unhide warnings/errors.

**Comment by Kirpich30000** [comment]
It would be nice also to parse DebugServer (scripts) output and populate Error List

**Comment by johnny-keker** [comment]
Works as described on `dev-stable`.
