### ISSUE TITLE
Allow RAD debugger to be used in C++ projects

### ISSUE THREAD

**Issue by timlathy** [vsrad/radeon-asm-tools#74]
The starting point is adding the `VisualC` capability to `AppliesTo` ([relevant sample](https://github.com/microsoft/VSProjectSystem/tree/master/samples/CpsExtension)). Points to consider:
* `.user.json` should not be created unless required (e.g. only when launching our debugger for the first time in a project)
* not all components that apply to our custom project capability should run in C++ projects (things like `IPasteDataObjectProcessor` will likely interfere with the default behavior)
* tool window instantiation should be delayed, currently done on project load (accesses project options so needs `.user.json`, also may negatively affect startup time)

To keep the necessary changes minimal I think we should look into rewriting `ProjectLifecycle` so that it creates dependent components and fires project load events lazily.

**Comment by Kirpich30000** [comment]
- `.user.json` should not be created unless user creates a profile. Error message should be shown if any RAD action (debug/profile/...) is started while profile is not selected.
- RAD `Build` action will not be supported in C++ projects (at least in the first version).
