### ISSUE TITLE
Add an option to deploy currently open file separately

### ISSUE THREAD

**Issue by timlathy** [vsrad/radeon-asm-tools#75]
In profile options:
* Rename ***Copy sources to remote*** to ***Copy project files and additional sources***
* Add an option to ***Copy currently open file as*** with a text field to rename the file on the remote machine (leaving it empty preserves the original filename)

No changes to debug server are necessary, the file should be renamed when constructing an archive on the VS side.

If the currently open file is not renamed, belongs to the project, and  ***Copy project files*** is enabled, we may end up with a duplicate file in the archive. This should be easy to dedupe. In case of name conflicts, ***Copy currently open file as*** should take precedence (?)

The biggest hurdle I see is adding a text field next to a checkbox in profile options, this will require a new attribute and changes to `ProfileOptionsReflector`.

**Comment by Kirpich30000** [comment]
It's ok to add separate checkbox `Copy currently open file` and a text field on the next line

**Comment by timlathy** [comment]
Is this issue still relevant after #90?

**Comment by Kirpich30000** [comment]
Since we are going to redesign that part of the extension it's better to close the issue and leave current functionality as is.
