### ISSUE TITLE
Enable font and background color highlighting for both rows and colors

### ISSUE THREAD

**Issue by Kirpich30000** [vsrad/radeon-asm-tools#87]
Rename current right click menu items and add missing `Font Color` and `Backgnd Color` for both rows and columns. Priority for chosing colors:
1. if cell is inactive use `Inactive` colors
2. else if row color is applied use row color
3. else if column color is applied use column color

**Comment by timlathy** [comment]
One issue left: unlike column colors, row colors do not get updated if *Data - Highlight Color* in changed in *Fonts and Colors* (the project needs to be closed and reopened to apply the changes).

To handle that, we'd need to save color settings for each row, is it okay to store them as a `watch name -> color` mapping? This'd mean that all watches with the same name will be highlighted the same.
